volumes:
  mongo_data:
  prometheus_data:
  grafana_data:

services:
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"

  api:
    build: .
    image: msterhuj/fastonboard_api
    command: --log-level=debug --workers=6
    environment:
      - APP=api
      - SECRET_KEY=secret
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
    ports:
      - "8000:8000"
    depends_on:
      - redis

  flower:
    build: .
    image: msterhuj/fastonboard_api
    environment:
      - APP=flower
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
    ports:
      - "5555:5555"
    depends_on:
      - redis

  beat:
    build: .
    image: msterhuj/fastonboard_api
    command: --loglevel=debug
    environment:
      - APP=beat
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
    depends_on:
      - redis

  worker:
    build: .
    image: msterhuj/fastonboard_api
    environment:
      - APP=worker
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
      - FLOWER_UNAUTHENTICATED_API=true
    depends_on:
      - redis
