# Deployment for pre-production environment
volumes:
  database:

services:

  redis:
    image: redis

  mariadb:
    image: mariadb
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
    volumes:
      - database:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: --log-level=info --workers=6
    image: ghcr.io/laboinfra/fob-api:${VERSION}
    env_file:
      - .env
    environment:
      - APP=api
    ports:
      - "127.0.0.1:8085:8000"
    depends_on:
      - redis
      - mariadb

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/laboinfra/fob-api:${VERSION}
    env_file:
      - .env
    environment:
      - APP=worker
    depends_on:
      - redis
      - mariadb

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/laboinfra/fob-api:${VERSION}
    command: --loglevel=debug
    env_file:
      - .env
    environment:
      - APP=beat
    depends_on:
      - redis
      - mariadb
