"""set unique for username and email

Revision ID: 5541b16183e2
Revises: 91572ab71ba1
Create Date: 2024-11-19 22:00:26.332257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5541b16183e2'
down_revision: Union[str, None] = '91572ab71ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("username", 'user', ['username'])
    op.create_unique_constraint("email", 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("username", 'user', type_='unique')
    op.drop_constraint("email", 'user', type_='unique')
    # ### end Alembic commands ###
