"""add subnet list for user class

Revision ID: ec4a669f208a
Revises: e98c81fd511d
Create Date: 2024-11-06 09:39:32.660838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec4a669f208a'
down_revision: Union[str, None] = 'e98c81fd511d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('allowed_subnets', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'allowed_subnets')
    # ### end Alembic commands ###
