"""drop deprecated col

Revision ID: a28c3a3aa218
Revises: 90979cd11ef8
Create Date: 2024-12-18 20:23:54.461569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a28c3a3aa218'
down_revision: Union[str, None] = '90979cd11ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'allowed_subnets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('allowed_subnets', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
