"""add user password reset class

Revision ID: 91572ab71ba1
Revises: ec4a669f208a
Create Date: 2024-11-19 20:11:09.396077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '91572ab71ba1'
down_revision: Union[str, None] = 'ec4a669f208a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userpasswordreset',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('token', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('source_ip', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('expires_at', mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_uca1400_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userpasswordreset')
    # ### end Alembic commands ###
