"""add headscale policy models

Revision ID: 90979cd11ef8
Revises: 5541b16183e2
Create Date: 2024-12-10 22:23:58.909282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90979cd11ef8'
down_revision: Union[str, None] = '5541b16183e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headscalepolicyacl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('src', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dst', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('headscalepolicygroupmember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'member', name='unique_group_name_member')
    )
    op.create_table('headscalepolicyhost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'ip', name='unique_host_name_ip')
    )
    op.create_table('headscalepolicytagownermember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'member', name='unique_owner_tag_name_member')
    )
    op.create_foreign_key(None, 'userpasswordreset', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userpasswordreset', type_='foreignkey')
    op.drop_table('headscalepolicytagownermember')
    op.drop_table('headscalepolicyhost')
    op.drop_table('headscalepolicygroupmember')
    op.drop_table('headscalepolicyacl')
    # ### end Alembic commands ###
