"""add unique to project name

Revision ID: aa1757ace187
Revises: 95f183d7afd0
Create Date: 2025-02-03 20:39:01.139616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa1757ace187'
down_revision: Union[str, None] = '95f183d7afd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'openstack_project', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'openstack_project', type_='unique')
    # ### end Alembic commands ###
