services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
