volumes:
  postgres_data:
  mariadb_data:

services:
  devcontainer:
    container_name: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
 
  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  keystone:
    image: docker.io/openstackhelm/keystone:2024.1-ubuntu_jammy
    container_name: keystone
    command: sleep infinity

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_USER: fastonboard
      MARIADB_PASSWORD: fastonboard
      MARIADB_DATABASE: fastonboard
      MARIADB_ROOT_PASSWORD: fastonboard
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
