volumes:
  postgres_data:
  mariadb_data:
  headscale_data:

services:
  devcontainer:
    container_name: devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock

  #traefik:
  #  image: traefik:v3.4
  #  container_name: traefik
  #  volumes:
  #    - ./config:/etc/traefik/
    #ports:
    #  - "8443:443"
    #  - "8180:80"
    #  - "8180:8080"
    #  - "8182:8082"
    #  - "8183:8083"

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"

  headscale:
    image: headscale/headscale:0.23
    container_name: headscale
    volumes:
      - ./config:/etc/headscale
      - headscale_data:/var/lib/headscale
    ports:
      - "8045:8080"
      - "8046:9090"
    command: serve --config /etc/headscale/headscale.yml

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_USER: fastonboard
      MARIADB_PASSWORD: fastonboard
      MARIADB_DATABASE: fastonboard
      MARIADB_ROOT_PASSWORD: fastonboard
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
